action_selector: multinomial
agent: iac_recursive_ac
agent_model: iac_recursive
agent_output_type: policies
iac_critic_use_sampling: True
iac_epsilon_start: 0.5
iac_epsilon_finish: 0.05
iac_epsilon_time_length: 20000
iac_epsilon_decay_mode: "exp"
iac_exploration_mode: "softmax"
iac_use_entropy_regularizer: False
iac_entropy_loss_regularization_factor: 0.000005
gamma: 0.99
learner: iac_q
lr_agent: 5e-4
lr_critic: 5e-4
multiagent_controller: iac_mac
n_critic_learner_reps: 54
obs_last_action: True
runner: iac
target_critic_update_interval: 661500
td_lambda: 0.8
use_replay_buffer: False


