multiagent_controller: pomace_mac
pomace_lambda_size: 10
pomace_epsilon_start: 5.0
pomace_epsilon_finish: 0.0001
pomace_epsilon_time_length: 20000
pomace_epsilon_size: 10
pomace_use_epsilon_seed: True
pomace_random_seed_max: 10000000000
pomace_multiagent_network: pomace_noise_multiagent_nn1
pomace_noise_network: pomace_noise_nn1
pomace_noise_hidden_layer_size: 64
runner: pomace
