multiagent_controller: mcce_mac
mcce_epsilon_start: 1.0
mcce_epsilon_finish: 0.05
mcce_epsilon_time_length: 100000
mcce_epsilon_size: 32
mcce_use_epsilon_seed: True
mcce_random_seed_max: 10000000000
mcce_multiagent_network: mcce_policy_multiagent_nn
mcce_coordination_network: mcce_policy_coordination_nn
mcce_decentralized_policy_network: mcce_policy_decentralized_policy_nn
mcce_coordination_network_hidden_layer_size: 64
runner: mcce
