agents_encoder_size: 64
agents_hidden_state_size: 64
mongodb_profile: gandalf_pymarl
n_loops_per_thread_or_sub_or_main_process: 0
n_threads_per_subprocess_or_main_process: 0
n_subprocesses: 0
observe: True
observe_db: True
run_mode: sequential
save_model: False
share_agent_params: True
tensorboard: True
test_interval: 8000
test_nepisode: 50
use_tensorboard: True
t_max: 100000000
use_cuda: True

