action_selector: "epsilon_greedy"
agent: "basic_ac"
agent_model: "RNN"
agent_encoder: "fc_encoder"
agent_output_type: "qvalues"
buffer_size: 1000
gamma: 0.99
vdn_epsilon_start: 0.5
vdn_epsilon_finish: 0.05
vdn_epsilon_time_length: 20000
vdn_epsilon_decay_mode: "exp"
learner: "vdn"
lr_q: 5e-4
multiagent_controller: "vdn_mac"
obs_last_action: True
runner: "vdn"
target_update_interval: 10000
td_lambda: 0
use_replay_buffer: True
vdn_mixing_network: "vdn_mixing_network"
vdn_mixer_model: "vdn_mixer"
vdn_use_state: False