action_selector: "epsilon_greedy"
agent: "rnn"
# agent_output_type: "qvalues"
batch_size: 32
batch_size_run: 1
buffer_size: 500
# defaults: default iql predator_prey
env: "pred_prey"
env_args:
  predator_prey_toroidal: False
  predator_prey_shape:
    - 4
    - 4
  n_prey: 1
  agent_obs:
    - 1
    - 1
  episode_limit: 50
  n_agents: 4
  reward_capture: 1
  reward_almost_capture: 0
  truncate_episodes: True
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 20000
test_nepisode: 20
test_interval: 2000
log_interval: 2000
target_update_interval: 200
rnn_hidden_dim: 64
t_max: 100000
gamma: 0.99

mac: "basic_mac"
obs_agent_id: True
obs_last_action: True
learner: "q_learner"
lr: 0.0005
grad_norm_clip: 40
runner: "episode"

use_cuda: False
use_tensorboard: False
save_model: False