# --- COMA specific parameters ---

action_selector: "multinomial"
epsilon_start: .0
epsilon_finish: .0
epsilon_anneal_time: 50000

runner: "parallel"
t_max: 500000

buffer_size: 32
batch_size_run: 32
batch_size: 32

# update the target network every {} training steps
target_update_interval: 250

lr: 0.0008
critic_lr: 0.0008
td_lambda: 0.7

# use COMA
agent_output_type: "pi_logits"
learner: "coma_learner"
mixer: # mixer becomes None

name: "coma"
