# --- COMA specific parameters ---

action_selector: "multinomial"
epsilon_start: .0
epsilon_finish: .0
epsilon_anneal_time: 50000

runner: "parallel"

buffer_size: 8
batch_size_run: 8
batch_size: 8

# update the target network every {} training steps
target_update_interval: 500

lr: 0.001
critic_lr: 0.001
td_lambda: 0.8

# use COMA
agent_output_type: "pi_logits"
learner: "coma_learner"

name: "coma"
