# --- COMA specific parameters ---

action_selector: "multinomial"
epsilon_start: 1.0
epsilon_finish: .05
epsilon_anneal_time: 20000

runner: "episode"
t_max: 500000

buffer_size: 32
batch_size_run: 1
batch_size: 32

# update the target network every {} episodes
target_update_interval: 100
lr: 0.0005

# use COMA
agent_output_type: "pi_logits"
learner: "coma_learner"
mixer: # mixer becomes None

name: "coma"
