# --- COMA specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 50000

runner: "parallel"
t_max: 500000

buffer_size: 32
batch_size_run: 32
batch_size: 32

# update the target network every {} episodes
target_update_interval: 1000

lr: 0.0005
td_lambda: 0.8

# use COMA
agent_output_type: "pi_logits"
learner: "coma_learner"
mixer: # mixer becomes None

name: "coma"
