# --- PPO specific parameters ---
action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 100000
mask_before_softmax: True

runner: "parallel"

buffer_size: 8
batch_size_run: 8
batch_size: 8

lr_actor: 0.0005
lr_critic: 0.0005
tau: 0.995
td_lambda: 0.99

agent_output_type: "pi_logits"
learner: "fixed_kl_learner"
critic: "independent_rnn_critic"

mini_epochs_actor: 15 
mini_epochs_critic: 10
entropy_loss_coeff: 0.001

# calculating advantage: GAE, TD_Error
advantage_calc_method: "GAE"

# adaptive kl param
kl_coeff_beta: 3.0

is_advantage_normalized: True
is_observation_normalized: True
is_popart: True
is_value_normalized: False

obs_agent_id: True
obs_last_action: False

name: "fixed_kl_rnn"