# --- Agent parameters ---
agent: "conv1d" # Default rnn agent
rnn_hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: False # Include the agent's one_hot id in the observation
obs_last_action: False # Include the agent's last action (one_hot) in the observation

# --- PPO specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 100000
mask_before_softmax: True

runner: "parallel"

buffer_size: 8
batch_size_run: 8
batch_size: 8

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 200


lr: 0.0005
critic_lr: 0.0005
td_lambda: 0.8

# use COMA
agent_output_type: "pi_logits"
learner: "ppo_learner"
critic_q_fn: "conv1d_critic"
critic_baseline_fn: "conv1d_critic"
critic_train_mode: "seq"
critic_train_reps: 1
q_nstep: 1 # 1 corresponds to normal r + gammaV

mini_epochs_num: 1
mini_batches_num: 2
entropy_loss_coeff: 0.001

ppo_policy_clip_param: 0.2

is_advantage_normalized: True
is_observation_normalized: True


name: "centralV"
