# --- Agent parameters ---
agent: "conv1d" 
obs_agent_id: False # Include the agent's one_hot id in the observation
obs_last_action: False # Include the agent's last action (one_hot) in the observation

# --- PPO specific parameters ---

action_selector: "multinomial"
mask_before_softmax: True

runner: "parallel"

buffer_size: 8
batch_size_run: 8
batch_size: 8

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 200

lr_actor: 0.0002
lr_critic: 0.0005
tau: 0.995
td_lambda: 0.97

agent_output_type: "pi_logits"
learner: "ppo_learner"
critic: "conv1d_critic"

mini_epochs_num: 2
mini_batches_num: 16
entropy_loss_coeff: 0.01
critic_loss_coeff: 1.0

ppo_policy_clip_param: 0.2

is_advantage_normalized: True
is_observation_normalized: True
is_separate_actor_critic: True

name: "ppo_conv1d"
