# --- PPO specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 100000
mask_before_softmax: True

runner: "parallel"

buffer_size: 8
batch_size_run: 8
batch_size: 8

# update the target network every {} training steps
target_update_interval: 200


lr_actor: 0.0005
lr_critic: 0.0005
tau: 0.995
td_lambda: 0.99

# use COMA
agent_output_type: "pi_logits"
learner: "ppo_learner"
critic: "rnn"

mini_epochs_num: 2
mini_batches_num: 8
entropy_loss_coeff: 0.1
critic_loss_coeff: 1.0

ppo_policy_clip_param: 0.2

is_advantage_normalized: True
is_observation_normalized: True
is_separate_actor_critic: True
is_central_value: False
actor_critic_mode: False
obs_agent_id: False
obs_last_action: False

name: "ppo_rnn"

