# --- Agent parameters ---
agent: "rnn" # Default rnn agent
rnn_hidden_dim: 64 # Size of hidden state for default rnn agent
obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation

# --- PPO specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 100000
mask_before_softmax: True

runner: "parallel"

buffer_size: 8
batch_size_run: 8
batch_size: 8

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 200


lr_actor: 0.0002
lr_critic: 0.0005
tau: 0.995
td_lambda: 0.97

# use COMA
agent_output_type: "pi_logits"
learner: "ppo_learner"
critic: "central_v"
critic_baseline_fn: "centralV"
critic_train_mode: "seq"
critic_train_reps: 1
q_nstep: 1 # 1 corresponds to normal r + gammaV

mini_epochs_actor: 4
mini_epochs_critic: 2
entropy_loss_coeff: 0.000

ppo_policy_clip_param: 0.2

is_advantage_normalized: True
is_observation_normalized: False
is_separate_actor_critic: True

name: "centralV"
