action_selector: multinomial
agent: xxx_recursive_ac
agent_model: xxx_recursive
agent_output_type: policies
agent_level1_share_params: True
agent_level2_share_params: True
agent_level3_share_params: True
critic_level1_share_params: True
critic_level2_share_params: True
critic_level3_share_params: True
lr_agent_level1: 5e-4
lr_agent_level2: 5e-4
lr_agent_level3: 5e-4
lr_critic_level1: 5e-4
lr_critic_level2: 5e-4
lr_critic_level3: 5e-4
xxx_agent_model_level1: xxx_recurrent_agent_level1
xxx_agent_model_level2: xxx_recurrent_agent_level2
xxx_agent_model_level3: xxx_recurrent_agent_level3
xxx_agent_level1_use_past_actions: True
xxx_agent_level2_use_past_actions: True
xxx_agent_level3_use_past_actions: True
xxx_agent_level3_use_past_actions_level1: True
xxx_critic_level1: xxx_critic_level1
xxx_critic_level2: xxx_critic_level2
xxx_critic_level3: xxx_critic_level3
xxx_critic_level1_use_past_actions: True
xxx_critic_level2_use_past_actions: True
xxx_critic_level3_use_past_actions: True
xxx_critic_level3_use_obs: True
xxx_critic_level2_use_past_actions_level1: True
xxx_critic_use_sampling: True
xxx_epsilon_start_level1: 0.5
xxx_epsilon_start_level2: 0.5
xxx_epsilon_start_level3: 0.5
xxx_epsilon_finish_level1: 0.05
xxx_epsilon_finish_level2: 0.05
xxx_epsilon_finish_level3: 0.05
xxx_epsilon_time_length_level1: 20000
xxx_epsilon_time_length_level2: 20000
xxx_epsilon_time_length_level3: 20000
xxx_epsilon_decay_mode_level1: "exp"
xxx_epsilon_decay_mode_level2: "exp"
xxx_epsilon_decay_mode_level3: "exp"
xxx_epsilon_start: 0.5
xxx_epsilon_finish: 0.05
xxx_epsilon_time_length: 20000
xxx_epsilon_decay_mode: "exp"
xxx_exploration_mode_level1: "softmax"
xxx_exploration_mode_level2: "softmax"
xxx_exploration_mode_level3: "softmax"
xxx_use_entropy_regularizer: False
xxx_use_obs_intersections: True
xxx_entropy_loss_regularization_factor: 0.000005
xxx_independent_logit_bias: False
gamma: 0.99
learner: xxx
multiagent_controller: xxx_mac
n_critic_learner_reps: 54
obs_last_action: True
runner: xxx
T_target_critic_level1_update_interval: 661500
T_target_critic_level2_update_interval: 661500
T_target_critic_level3_update_interval: 661500
target_critic_update_interval: 661500
td_lambda: 0.8
use_replay_buffer: False


