# ---- Defaults for 4 agents hunting 1 stag and 1 hare in a 10x10 environment

env: "PredatorPrey7x7P-2-v0"

test_nepisode: 16
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 300000
