# --- Defaults for SC2, only positive rewards, max cumulative reward=20 ---

env: sc2

env_stats_aggregator: "sc2"

env_args:
  map_name: "3m_3m" # 3 marines by default
  difficulty: "3"
  heuristic: False
  measure_fps: True
  move_amount: 2
  reward_death_value: 10
  reward_negative_scale: 0.5
  reward_only_positive: True
  reward_scale: True
  reward_scale_rate: 20
  reward_win: 200
  state_last_action: True
  step_mul: 8
  obs_ignore_ally: False
  obs_instead_of_state: False
  continuing_episode: False
  game_version: "3.16.1"
