action_selector: "epsilon_greedy"
agent: "basic_ac"
agent_model: "RNN"
agent_output_type: "qvalues"
buffer_size: 1000
gamma: 0.99
iql_epsilon_start: 0.5
iql_epsilon_finish: 0.05
iql_epsilon_time_length: 20000
iql_epsilon_decay_mode: "exp"
learner: "iql"
lr_q: 5e-4
multiagent_controller: "independent_mac"
obs_last_action: True
runner: "iql"
target_update_interval: 2000
td_lambda: 0
use_replay_buffer: True
use_full_observability: False
has_target_network: True