action_selector: multinomial
agent: mackrel_recursive_ac
agent_model: mackrel_recursive
agent_output_type: policies
agent_level1_share_params: True
agent_level2_share_params: True
agent_level3_share_params: True
critic_level1_share_params: True
critic_level2_share_params: True
critic_level3_share_params: True
lr_agent_level1: 5e-4
lr_agent_level2: 5e-4
lr_agent_level3: 5e-4
lr_critic_level1: 5e-4
lr_critic_level2: 5e-4
lr_critic_level3: 5e-4
mackrel_agent_model_level1: mackrel_recurrent_agent_level1
mackrel_agent_model_level2: mackrel_recurrent_agent_level2
mackrel_agent_model_level3: mackrel_recurrent_agent_level3
mackrel_agent_level1_use_past_actions: True
mackrel_agent_level2_use_past_actions: True
mackrel_agent_level3_use_past_actions_level2: True
mackrel_agent_level3_use_past_actions: True
mackrel_agent_level3_use_past_actions_level1: True
mackrel_critic_level1: mackrel_critic_level1
mackrel_critic_level2: mackrel_critic_level2
mackrel_critic_level3: mackrel_critic_level3
mackrel_critic_level1_use_past_actions: True
mackrel_critic_level2_use_past_actions: True
mackrel_critic_level3_use_past_actions: True
mackrel_critic_level3_use_obs: True
mackrel_critic_level2_use_past_actions_level1: True
mackrel_critic_use_sampling: True
mackrel_epsilon_start_level1: 0.5
mackrel_epsilon_start_level2: 0.5
mackrel_epsilon_start_level3: 0.5
mackrel_epsilon_finish_level1: 0.05
mackrel_epsilon_finish_level2: 0.05
mackrel_epsilon_finish_level3: 0.05
mackrel_epsilon_time_length_level1: 20000
mackrel_epsilon_time_length_level2: 20000
mackrel_epsilon_time_length_level3: 20000
mackrel_epsilon_decay_mode_level1: "exp"
mackrel_epsilon_decay_mode_level2: "exp"
mackrel_epsilon_decay_mode_level3: "exp"
mackrel_exploration_mode_level1: "softmax"
mackrel_exploration_mode_level2: "softmax"
mackrel_exploration_mode_level3: "softmax"
mackrel_use_entropy_regularizer: False
mackrel_use_obs_intersections: True
mackrel_entropy_loss_regularization_factor: 0.000005
mackrel_delegation_probability_bias: 0.5
gamma: 0.99
learner: mackrel
multiagent_controller: mackrel_mac
n_critic_learner_reps: 54
n_pair_samples: ~
obs_last_action: True
runner: mackrel
T_target_critic_level1_update_interval: 661500
T_target_critic_level2_update_interval: 661500
T_target_critic_level3_update_interval: 661500
target_critic_update_interval: 661500
td_lambda: 0.8
use_replay_buffer: False
mackrel_logit_bias: 1.5
use_batch_norm: True
use_full_observability: False



