env: sc1
env_args:
  difficulty: "3"
  episode_limit: 70
  heuristic_function: False
  measure_fps: True
  move_amount: 5
  reward_death_value: 10
  reward_negative_scale: 0.5
  reward_only_positive: True
  reward_scale: False
  reward_scale_rate: 0
  reward_win: 30
  state_last_action: True
  step_mul: 7