action_selector: "epsilon_greedy"
agent: "basic_ac"
agent_model: "RNN"
agent_encoder: "fc_encoder"
agent_output_type: "qvalues"
buffer_size: 1000
gamma: 0.99
learner: "qmix"
lr_q: 5e-4
multiagent_controller: "qmix_mac"
obs_last_action: True
qmix_epsilon_start: 0.5
qmix_epsilon_finish: 0.05
qmix_epsilon_time_length: 20000
qmix_epsilon_decay_mode: "exp"
qmix_mixing_network: "qmix_mixing_network"
qmix_mixer_model: "qmix_mixer"
qmix_use_state: False
runner: "qmix"
target_update_interval: 10000
td_lambda: 0
use_replay_buffer: True
