action_selector: multinomial
agent: coma_recursive_ac
agent_model: coma_recursive
agent_output_type: policies
coma_critic_use_sampling: True
coma_epsilon_start: 0.5
coma_epsilon_finish: 0.05
coma_epsilon_time_length: 20000
coma_epsilon_decay_mode: "exp"
coma_exploration_mode: "softmax"
coma_use_entropy_regularizer: False
coma_entropy_loss_regularization_factor: 0.000005
gamma: 0.99
learner: coma
lr_agent: 5e-4
lr_critic: 1e-3
multiagent_controller: coma_mac
n_learner_reps: 50
obs_last_action: True
runner: coma
target_critic_update_interval: 661500
td_lambda: 0.8
use_replay_buffer: False


